### PR TITLE
Fix tickable sounds not working

### LINKED ISSUE #25: Minecart sounds are not mufflable
**Versions**
Indicate the versions for:
- Extreme sound muffler 3.9 and 3.10
- Forge 36.1.0

**Describe the bug**
Minecart sounds are not mufflable.

**To Reproduce**
1. Open the sound muffler GUI
2. Change the volume of `entity.minecart.riding:minecraft` and `entity.minecart.inside:minecraft` to something like 90%
3. No minecart sound plays at all

**Expected behavior**
The sound to be playing with 90% volume

**Screenshots or Crashlog**
image

**Additional context**
I think the problem is because these sounds are `TickableSound` sounds.

Another problem is muffling the sound of cars from the [Ultimate Car Mod](https://github.com/henkelmax/ultimate-car-mod) or planes of the [Ultimate Plane Mod](https://github.com/henkelmax/ultimate-plane-mod).
When reducing the volume of these sounds, it causes the sound to be stacked infinitely.

https://user-images.githubusercontent.com/13237524/118011169-01917e80-b350-11eb-911a-eb570438a695.mp4

### PR DESCRIPTION
**Pull request by henkelmax**
Closes #25

### CODE REVIEW

**Comment by LeoBeliik** [comment]
I've noticed it doesn't work with Anchors, could you make it muffle the sounds when they're inside the area?

**Comment by henkelmax** [comment]
Sorry, that was an oversight by me. It should be fixed.

**Comment by LeoBeliik** [comment]
It looks good to me.
Thank you very much for the help 😄

**Comment by henkelmax** [comment]
No problem :)

**Pull request merged**
